name: Scan multiple repos on push

on:
  push:
    branches:
      - main

jobs:
  scan-repos:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout scan repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download Endorctl
        run: |
            curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl;
            echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c;
            if [ $? -ne 0 ]; then 
             echo "Integrity check failed"; 
             exit 1;
            fi
            chmod +x ./endorctl
            mkdir -p $HOME/bin
            mv endorctl $HOME/bin/endorctl
            echo "$HOME/bin" >> $GITHUB_PATH

      - name: Authenticate to Endor Labs using API key
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ENDOR_NAMESPACE: tej-learn
          ENDOR_API_KEY: ${{ secrets.ENDOR_API_KEY }}
          ENDOR_API_SECRET: ${{ secrets.ENDOR_API_SECRET }}
        run: |
          endorctl auth login \
          --api-key "$ENDOR_API_KEY" \
          --api-secret "$ENDOR_API_SECRET" \
          --namespace "$ENDOR_NAMESPACE"

      - name: Scan repositories and tag projects
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ENDOR_NAMESPACE: tej-learn
          ENDOR_API_KEY: ${{ secrets.ENDOR_API_KEY }}
          ENDOR_API_SECRET: ${{ secrets.ENDOR_API_SECRET }}
        run: |
          jq -c '.[]' repos.json | while read repo; do
            NAME=$(echo "$repo" | jq -r '.name')
            BU_TAG=$(echo "$repo" | jq -r '.BU_TAGS')

            echo "🔍 Scanning repo: $NAME"
            echo "🏷 BU Tag: $BU_TAG"

            git clone https://github.com/tejjnayak/$NAME.git
            cd $NAME

            if [ -n "$BU_TAG" ] && [ "$BU_TAG" != "null" ]; then
              endorctl scan \
                --namespace "$ENDOR_NAMESPACE" \
                --project-tags "bu=$BU_TAG"
            else
              endorctl scan \
                --namespace "$ENDOR_NAMESPACE"
            fi

            cd ..
            rm -rf "$NAME"
          done
